# Default values for kube-arbitrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: kubearbitrator/xqueuejob-ctrl
  tag: v0.16
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 2000m
    memory: 2048Mi

serviceAccount: xqueuejob-controller

nodeSelector: 
 hostname:

